version: '2'
services:
  jenkins:
    #image: 'jenkins:2.46.2'
    image: jenkins
    ports:
      - "8080:8080"
    volumes:
      - './data:/var/jenkins_home'

networks:
  default:
    external:
      name: shared
